name: ci

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    name: Lint & Test (tolerant)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          pip install ruff black pytest duckdb pandas

      - name: Run Lint (non-blocking)
        run: |
          ruff check. || true
          black --check. || true

      - name: Run Tests (non-blocking)
        run: |
          pytest -q --maxfail=1 --disable-warnings || true
