name: ci

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    name: Lint & Test (lightweight)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install minimal deps for CI
        run: |
          python -m pip install --upgrade pip
          # Only what's needed for tests + lint; heavy libs are skipped
          pip install ruff black pytest duckdb pandas

      - name: Lint
        run: |
          ruff check .
          black --check .

      - name: Run tests
        run: |
          pytest -q --maxfail=1 --disable-warnings
